from pathlib import Path
import csv
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (BaseDocTemplate, PageTemplate, Frame, Paragraph,
    Spacer, PageBreak, NextPageTemplate, Table, TableStyle, Image, KeepTogether)

ROOT = Path(__file__).resolve().parents[1]
# Keep the previously delivered PDF unchanged so the editor can review a
# textual diff before replacing it.  The revised artifact is written beside it.
OUT = ROOT / 'paper' / 'ICEBA2026_submission_revised.pdf'
FIG = ROOT / 'Figures'

for name, path in [('Arial', r'C:\Windows\Fonts\arial.ttf'),
                   ('Arial-Bold', r'C:\Windows\Fonts\arialbd.ttf'),
                   ('Arial-Italic', r'C:\Windows\Fonts\ariali.ttf')]:
    if Path(path).exists():
        pdfmetrics.registerFont(TTFont(name, path))
font = 'Arial' if 'Arial' in pdfmetrics.getRegisteredFontNames() else 'Helvetica'
bold = 'Arial-Bold' if 'Arial-Bold' in pdfmetrics.getRegisteredFontNames() else 'Helvetica-Bold'
italic = 'Arial-Italic' if 'Arial-Italic' in pdfmetrics.getRegisteredFontNames() else 'Helvetica-Oblique'

styles = getSampleStyleSheet()
styles.add(ParagraphStyle('PaperTitle', parent=styles['Title'], fontName=bold, fontSize=17, leading=20, alignment=TA_CENTER, spaceAfter=7))
styles.add(ParagraphStyle('Anon', parent=styles['Normal'], fontName=font, fontSize=9.2, leading=12, alignment=TA_CENTER, textColor=colors.HexColor('#444444'), spaceAfter=12))
styles.add(ParagraphStyle('Abstract', parent=styles['Normal'], fontName=font, fontSize=9.3, leading=12.2, alignment=TA_JUSTIFY, leftIndent=8, rightIndent=8, spaceAfter=5))
styles.add(ParagraphStyle('Keywords', parent=styles['Normal'], fontName=font, fontSize=8.7, leading=11, leftIndent=8, rightIndent=8, spaceAfter=12))
styles.add(ParagraphStyle('H1x', parent=styles['Heading1'], fontName=bold, fontSize=11.5, leading=14, spaceBefore=8, spaceAfter=4, keepWithNext=True))
styles.add(ParagraphStyle('H2x', parent=styles['Heading2'], fontName=bold, fontSize=9.8, leading=12, spaceBefore=5, spaceAfter=2, keepWithNext=True))
styles.add(ParagraphStyle('Bodyx', parent=styles['BodyText'], fontName=font, fontSize=9.1, leading=11.8, alignment=TA_JUSTIFY, spaceAfter=4.5, firstLineIndent=9))
styles.add(ParagraphStyle('BodyNoIndent', parent=styles['BodyText'], fontName=font, fontSize=9.1, leading=11.8, alignment=TA_JUSTIFY, spaceAfter=4.5))
styles.add(ParagraphStyle('Caption', parent=styles['Normal'], fontName=italic, fontSize=7.7, leading=9.2, alignment=TA_CENTER, textColor=colors.HexColor('#444444'), spaceBefore=2, spaceAfter=7))
styles.add(ParagraphStyle('Ref', parent=styles['Normal'], fontName=font, fontSize=8.1, leading=10, leftIndent=10, firstLineIndent=-10, spaceAfter=2))

def P(txt, style='Bodyx'):
    return Paragraph(txt, styles[style])

def fig(name, caption, width=3.18*inch):
    path = FIG / name
    if not path.exists(): return []
    from PIL import Image as PILImage
    im = PILImage.open(path)
    h = width * im.height / im.width
    return [Image(str(path), width=width, height=h), Paragraph(caption, styles['Caption'])]

class PaperDoc(BaseDocTemplate):
    def __init__(self, filename):
        super().__init__(filename, pagesize=A4, leftMargin=16*mm, rightMargin=16*mm, topMargin=15*mm, bottomMargin=15*mm)
        full = Frame(self.leftMargin, self.bottomMargin, self.width, self.height, id='full', leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)
        gap = 5*mm; colw = (self.width-gap)/2
        left = Frame(self.leftMargin, self.bottomMargin, colw, self.height, id='left', leftPadding=0, rightPadding=2.5*mm, topPadding=0, bottomPadding=0)
        right = Frame(self.leftMargin+colw+gap, self.bottomMargin, colw, self.height, id='right', leftPadding=2.5*mm, rightPadding=0, topPadding=0, bottomPadding=0)
        self.addPageTemplates([PageTemplate(id='first', frames=[full], onPage=self.footer), PageTemplate(id='two', frames=[left,right], onPage=self.footer)])
    def footer(self, canvas, doc):
        canvas.saveState(); canvas.setStrokeColor(colors.HexColor('#bbbbbb')); canvas.setLineWidth(.3)
        canvas.line(doc.leftMargin, 10*mm, A4[0]-doc.rightMargin, 10*mm)
        canvas.setFont(font, 7.5); canvas.setFillColor(colors.HexColor('#555555'))
        canvas.drawString(doc.leftMargin, 6.5*mm, 'ICEBA 2026 | Anonymous submission')
        canvas.drawRightString(A4[0]-doc.rightMargin, 6.5*mm, f'Page {doc.page}')
        canvas.restoreState()

def table(data, widths, header=True):
    t=Table(data, colWidths=widths, repeatRows=1 if header else 0, hAlign='CENTER')
    st=[('FONTNAME',(0,0),(-1,-1),font),('FONTSIZE',(0,0),(-1,-1),7.2),('LEADING',(0,0),(-1,-1),8.5),('GRID',(0,0),(-1,-1),.25,colors.HexColor('#aaaaaa')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),3),('RIGHTPADDING',(0,0),(-1,-1),3)]
    if header: st += [('FONTNAME',(0,0),(-1,0),bold),('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e8eef5'))]
    t.setStyle(TableStyle(st)); return t

story=[]
story += [P('Leakage-Aware Evaluation of LLM, Tree, and Margin-Based Trading Systems on Two Decades of Gold and Apple Data','PaperTitle'), P('Anonymous Author(s)<br/>Affiliation omitted for double-blind review','Anon')]
story += [P('<b>Abstract.</b> This paper evaluates five trading systems—an unfiltered baseline, a rule-based market-disagreement filter (RMDB), support-vector machine (SVM), XGBoost, and a large language model (LLM)—under a common backtesting protocol. The primary benchmark uses real daily observations for gold and Apple from 2004–2025 and contains 120 runs spanning four chronological train/test windows, three transaction-cost assumptions, two assets, and five systems. Each decision is generated from information available at the decision date; returns are computed after slippage, and all models are assessed with total return, maximum drawdown, Sharpe ratio, and Sortino ratio. In the principal zero-cost scenario, the SVM has the least negative aggregate return (−2.92%) and the lowest drawdown (3.63%), while the LLM is weakest (−7.29% return; Sharpe −1.22). With the moderate-cost scenario used for the main comparison, the baseline and XGBoost are the only systems with positive aggregate returns (+2.07% and +1.73%), although their risk-adjusted advantages are small. Paired bootstrap intervals show a robust positive XGBoost–LLM return difference only in the highest-cost scenario. A separate shuffled/noisy-data audit, with LLM evaluation intentionally restricted to the S0 policy, is treated as an auxiliary memory-contamination check rather than as performance evidence. The results favor strict temporal evaluation, transparent cost accounting, and cautious claims about language-model trading performance.','Abstract'), P('<b>Keywords:</b> algorithmic trading; large language models; XGBoost; support-vector machines; backtesting; transaction costs; data leakage','Keywords'), Spacer(1,3), P('1. Introduction','H1x')]
intro=[
'Financial prediction studies frequently report improvements that disappear when a model is evaluated with realistic timing and trading frictions. The central difficulty is not only statistical prediction: a trading system must transform a dated information set into an executable position, incur costs, and survive changes in market regime. This paper therefore studies model comparison as an evaluation problem, rather than presenting a single high-performing predictor.',
'The study compares five systems with distinct inductive biases. A simple baseline establishes the performance of the shared signal pipeline; RMDB represents a transparent rule filter; SVM and XGBoost provide classical nonlinear machine-learning references; and an LLM represents a flexible, instruction-following decision-maker. The comparison is deliberately asymmetric in complexity: a more expressive model is useful only if its additional flexibility translates into out-of-sample economic value.',
'Two design choices are important. First, the primary benchmark is built from real daily gold and Apple observations covering 2004–2025, not from synthetic data. Chronological train/test windows preserve the forecasting direction and are repeated over four market periods. Second, transaction costs are varied explicitly. The resulting performance surface reveals whether an apparent advantage is economically meaningful or merely a consequence of frictionless accounting.',
'The paper also includes a restricted robustness audit. Price blocks are shuffled and lightly perturbed, dates and asset identifiers are neutralized, and the same evaluation machinery is rerun. These data are not an alternative market benchmark and are not used to claim profitability. Instead, they provide a falsification-oriented check against memorization or accidental dependence on recognizable historical names. Because LLM calls are expensive, the audit evaluates the LLM only under S0; this is a pre-specified resource constraint, not a missing cell in the primary experiment.',
'The contribution is empirical and procedural. We provide a common, leakage-aware comparison; separate primary evidence from the synthetic audit; report risk and cost sensitivity alongside returns; and use paired bootstrap intervals and casewise dominance counts to avoid over-interpreting a single aggregate. The resulting evidence suggests that evaluation discipline and transparent governance matter at least as much as model class when claims concern deployable trading systems.'
]
story += [P(x) for x in intro]
story += [P('Theoretical Framing','H1x'), P('<b>Leakage-Aware Validity Criteria (LAVC).</b> This study frames empirical validity as a conjunction of four criteria rather than as a single performance statistic. <b>C1—Temporal separation:</b> every fitted parameter and decision must be conditioned on information available no later than the forecast date; this criterion is operationalized by the chronological data construction and holdout windows in Section 3.1. <b>C2—Cost-realism:</b> reported economic value must survive explicitly stated execution frictions, with return and risk metrics recomputed under alternative slippage assumptions in Section 3.2. <b>C3—Contamination audit:</b> conclusions should be stress-tested after recognizable dates and asset identifiers are removed and observations are shuffled or perturbed; the auxiliary procedure is documented in Section 3.4. <b>C4—Uncertainty reporting:</b> aggregate rankings must be accompanied by sampling-based intervals and casewise dominance counts so that point estimates are not mistaken for simultaneous evidence of superiority; Section 3.3 specifies this reporting layer. Under LAVC, a model is considered empirically credible only to the extent that all four criteria are transparently addressed. The framework consequently separates evidence of predictive or economic association from stronger claims of deployability, robustness, or generalization beyond the evaluated assets and periods.','Bodyx')]
story += [P('2. Related Work','H1x'), P('Classical asset-pricing research frames return predictability as a joint hypothesis about information, risk, and market efficiency [1]. Technical-analysis systems operationalize information through indicators and rules [2], but their apparent success is highly sensitive to data snooping and implementation details. Machine-learning work has consequently emphasized carefully separated temporal samples and economically interpretable benchmarks.', 'Bodyx'), P('SVMs offer margin-based regularization for nonlinear classification [3], whereas gradient-boosted trees such as XGBoost combine weak learners with flexible interactions [4]. Recent finance applications also use SHAP-style additive explanations to inspect feature dependence [5]. These methods are strong references because they are reproducible, relatively inexpensive, and do not require free-form textual reasoning.', 'Bodyx'), P('Language models introduce a different risk profile. Their natural-language interface can integrate heterogeneous context, but prompt sensitivity, stochasticity, and hidden memorization complicate reproducibility. Prior work on chain-of-thought and finance-specific language models motivates careful separation between language capability and forecast information [6,8]. In portfolio research, frameworks such as FinRL further demonstrate the need to distinguish a predictive score from a fully specified execution policy [9]. Our protocol follows this distinction and reports the realized portfolio metrics after costs.', 'Bodyx'), P('3. Research Design and Methodology','H1x')]
story += [P('3.1 Data and temporal protocol','H2x'), P('The primary dataset contains daily market observations for gold and Apple (AAPL) from 2004 through 2025. For each asset, engineered predictors include lagged returns, moving averages and exponential moving averages, volatility and range measures, momentum oscillators, MACD components, and volume-derived ratios where available. The feature vector is constructed using only observations at or before the decision date. Four chronological train/test windows are used: 2005–2007→2008–2009, 2017–2019→2020–2021, 2019–2021→2022–2023, and 2021–2023→2024–2025. No future-period observation is used to fit a preceding test window.', 'Bodyx'), P('3.2 Systems and execution','H2x'), P('All systems produce a binary long/flat decision through the same backtest engine. The baseline uses the shared technical-signal rule without additional filtering. RMDB applies an interpretable disagreement filter. SVM uses a standardized feature matrix and regularized nonlinear classification; XGBoost uses gradient-boosted decision trees. The LLM receives a structured, dated feature summary and returns a constrained action under a fixed prompt contract. Portfolio returns are measured after the selected slippage assumption, with identical position sizing and exit logic across systems. This common execution layer prevents model-specific bookkeeping from driving the comparison.', 'Bodyx'), P('3.3 Metrics and uncertainty','H2x'), P('We report cumulative total return, maximum drawdown, Sharpe ratio, and Sortino ratio. Aggregate tables summarize eight asset/window cases per system and scenario. To quantify pairwise uncertainty, paired bootstrap resampling is applied to case-level return differences against the LLM; intervals that cross zero are treated as inconclusive. Casewise dominance counts record how often a comparator has higher return, lower drawdown, or higher Sharpe than the LLM. These summaries follow the principle that a single mean can conceal substantial cross-asset and cross-period variation [10].', 'Bodyx'), P('3.4 Auxiliary shuffled-data audit','H2x'), P('The robustness dataset is generated by block shuffling and small Gaussian perturbations, with dates and asset names blinded. It is designed to remove the original chronological market narrative while preserving a mechanically valid input shape. The audit has 104 runs: 24 each for Baseline, RMDB, SVM, and XGBoost, and eight LLM runs restricted to S0. Its purpose is diagnostic—testing whether a system produces unusually informed behavior when recognizable historical context is destroyed—not to replace the 120-run real-data benchmark.', 'Bodyx')]

story += [P('4. Results','H1x'), P('The primary aggregate results are shown for S1, the moderate-cost scenario selected for the main comparison. The baseline obtains the highest return (+2.07%) and a Sharpe ratio of 0.206. XGBoost is close (+1.73%) with materially lower drawdown (4.54% versus 8.12%). RMDB is approximately flat (−0.25%), while SVM sacrifices return (−1.91%) for the lowest drawdown (2.76%). The LLM remains positive in return (+0.46%) but has the largest drawdown among the positive-return systems and a negative Sharpe (−0.179).', 'Bodyx')]
data=[['System','Return %','MDD %','Sharpe','Sortino'],['Baseline','+2.07','8.12','0.206','0.319'],['RMDB','−0.25','7.84','0.028','0.062'],['SVM','−1.91','2.76','−0.299','−0.329'],['XGBoost','+1.73','4.54','0.204','0.242'],['LLM','+0.46','8.67','−0.179','−0.103']]
story += [table(data,[1.1*inch,.72*inch,.72*inch,.72*inch,.72*inch]), Paragraph('Table 1. Aggregate primary-benchmark performance under S1 (eight asset/window cases per system).',styles['Caption'])]
story += fig('fig01_total_return_distribution.jpg','Figure 1. Distribution of case-level total returns across the primary benchmark.',3.15*inch)
story += [P('Cost sensitivity changes the ranking. Under S0, SVM has the least negative aggregate return (−2.92%) and lowest drawdown (3.63%), while the LLM is worst on return (−7.29%) and Sharpe (−1.222). Under S2, the baseline is approximately flat (+0.27%) and XGBoost is slightly negative (−0.17%); SVM is −2.29% and the LLM −4.06%. Thus, the positive S1 results of the baseline and XGBoost are not invariant to friction assumptions.', 'Bodyx')]
story += fig('fig11_slippage_sensitivity_return.jpg','Figure 2. Aggregate return sensitivity to slippage assumptions.',3.15*inch)
story += [P('Pairwise uncertainty is similarly nuanced. The XGBoost–LLM return difference in S2 is +3.89 percentage points, with a 95% paired-bootstrap interval of [0.35, 7.39], the only reported interval excluding zero. The corresponding S0 and S1 intervals cross zero. SVM beats the LLM in return in 7/8 S0 cases and 6/8 S2 cases, but its intervals also cross zero; its main advantage is lower drawdown in 7/8 S0 and S1 cases. These results support a risk-aware, non-universal interpretation of model ranking.', 'Bodyx')]
story += fig('fig13_paired_bootstrap_delta.jpg','Figure 3. Paired-bootstrap return differences relative to the LLM.',3.15*inch)
story += [P('5. Interpretation, Governance, and Limitations','H1x'), P('The evidence does not establish that any system is a consistently profitable trading strategy. Instead, it illustrates a trade-off between return, drawdown, and friction sensitivity. The simple baseline performs best in the selected S1 aggregate, while XGBoost provides a similar return with lower drawdown. This is compatible with the view that flexible models can help when their interactions are aligned with a regime, but it does not imply that complexity is intrinsically valuable.', 'Bodyx'), P('The LLM results deserve particular caution. Negative or near-zero aggregate risk-adjusted performance may reflect prompt variance, constrained action semantics, or the difficulty of converting textual reasoning into a stable trading policy. The protocol therefore treats the LLM as a reproducible decision interface rather than as an oracle. Temperature, prompt version, dated input serialization, and raw decisions should be archived for an independent replication.', 'Bodyx'), P('Feature explanations provide a useful diagnostic rather than causal evidence. In the XGBoost analysis, one-day percentage change, EMA-50, and MACD histogram are among the largest mean absolute SHAP contributions. Their importance indicates where the fitted model places predictive weight; it does not prove that these variables generate a persistent risk premium. Explanation plots should consequently be read together with temporal holdout results.', 'Bodyx'), P('The governance implications are consistent with the risk-management orientation of the NIST AI Risk Management Framework (AI RMF): validity evidence, documented limitations, and traceable human oversight should accompany any transition from research backtest to operational use. They also align with the management-system perspective of ISO/IEC 42001, under which model documentation, accountability, monitoring, and controlled change are treated as lifecycle requirements. These frameworks do not validate the reported returns; rather, they provide governance lenses through which the LAVC criteria can be operationalized.', 'Bodyx')]
story += fig('fig16_xgboost_shap_summary.jpg','Figure 4. XGBoost SHAP summary for the fitted feature set.',3.15*inch)
story += [P('The shuffled/noisy audit strengthens governance claims only in a limited sense. If performance collapses when dates and names are neutralized, that is consistent with dependence on genuine temporal structure rather than memorized labels. However, synthetic perturbation is not a formal proof of no leakage, and the asymmetric LLM coverage prevents a complete robustness ranking. Future work should add repeated random seeds, nested walk-forward validation, and a matched-cost LLM audit.', 'Bodyx'), P('Several limitations remain. The universe contains only two assets; transaction costs are represented by slippage assumptions rather than a full market-impact model; and the number of independent asset/window cases is small. Hyperparameter selection and prompt design can still induce researcher degrees of freedom. Finally, aggregate metrics conceal turnover, exposure concentration, and tail behavior. These limitations motivate conservative claims and public release of manifests, configuration files, and raw decision logs.', 'Bodyx')]
story += fig('fig25_cumulative_equity_curves.jpg','Figure 5. Cumulative equity curves across the primary benchmark.',3.15*inch)
story += [P('6. Conclusion','H1x'), P('This study presents a leakage-aware comparison of a baseline, RMDB, SVM, XGBoost, and LLM trading system on real daily gold and Apple data from 2004–2025. Across four chronological windows, two assets, and three slippage assumptions, no model dominates every objective. The moderate-cost aggregate favors the baseline and XGBoost on return, while SVM provides the most conservative drawdown profile. Bootstrap and casewise analyses show that many apparent differences remain statistically or economically uncertain.', 'Bodyx'), P('The practical implication is methodological: deployable claims require a dated information boundary, a common execution engine, explicit costs, and uncertainty summaries. The shuffled/noisy experiment is best understood as an auxiliary contamination audit, with LLM evaluation limited to S0 by design. It should not be conflated with the real-data benchmark or used to imply broad robustness. The resulting paper is therefore a transparent evaluation artifact, not a promise of future trading profit.', 'Bodyx'), P('References','H1x')]
refs=['[1] Fama, E.F. Efficient capital markets: A review of theory and empirical work. Journal of Finance (1970).','[2] Murphy, J.J. Technical Analysis of the Financial Markets. New York Institute of Finance (1999).','[3] Cortes, C., Vapnik, V. Support-vector networks. Machine Learning 20, 273–297 (1995).','[4] Chen, T., Guestrin, C. XGBoost: A scalable tree boosting system. KDD (2016).','[5] Lundberg, S.M., Lee, S.-I. A unified approach to interpreting model predictions. NeurIPS (2017).','[6] Wei, J. et al. Chain-of-thought prompting elicits reasoning in large language models. NeurIPS (2022).','[7] López de Prado, M. Advances in Financial Machine Learning. Wiley (2018).','[8] Araci, D. FinBERT: Financial sentiment analysis with pre-trained language models. arXiv:1908.10063 (2019).','[9] Yang, H. et al. FinRL: A deep reinforcement learning library for automated stock trading. NeurIPS Workshop (2020).','[10] Efron, B., Tibshirani, R.J. An Introduction to the Bootstrap. Chapman & Hall (1994).','[11] Deng, S., Sakurai, K. Multiple-source stock prediction. IEEE International Conference on Data Mining Workshops (2014).']
story += [P(r,'Ref') for r in refs]

OUT.parent.mkdir(exist_ok=True)
doc=PaperDoc(str(OUT))
story.insert(0, NextPageTemplate('two'))
doc.build(story)
print(f'Wrote {OUT} ({OUT.stat().st_size} bytes)')
